// Draws Turbine's logo (assets/brand/turbine-logo.svg) as Braille frames for the terminal header and
// writes them to src/ui/logo-frames.ts. The mark (the first four paths) turns like a coin, about its
// vertical axis; the wordmark stays still. Run with `npm run logo:build` after changing this file or
// the SVG; a test checks the committed frames match.
import { readFileSync, writeFileSync } from "node:fs";

import { Resvg } from "@resvg/resvg-js";

type LogoSize = {
  width: number;
  height: number;
  markWidth: number;
  word: string[];
  mark: string[][];
};
type Logo = { full: LogoSize; compact: LogoSize };

const VIEW_WIDTH = 127;
const VIEW_HEIGHT = 24;
// The mark's vertical axis and right edge, in SVG units.
const MARK_AXIS = 11;
const MARK_EDGE = 23;
const MARK_PATHS = 4;
// Half a turn: the mark is mirror-symmetric, so 0° and 180° look the same and the loop is seamless.
const FRAMES = 16;
// Supersampling per Braille dot, and how much of a dot must be ink to light it.
const SAMPLES = 4;
const THRESHOLD = 0.45;
// Braille dot bits, by row (0–3) and column (0–1).
const BITS = [
  [0x01, 0x08],
  [0x02, 0x10],
  [0x04, 0x20],
  [0x40, 0x80],
] as const;
const SIZES = {
  full: { width: 74, height: 7 },
  compact: { width: 53, height: 5 },
};

function paths(svg: string): string[] {
  return [...svg.matchAll(/<path\b[^>]*\/>/g)].map((m) =>
    m[0].replace(/fill="[^"]*"/, 'fill="#000"')
  );
}

function braille(
  layer: string,
  width: number,
  height: number,
  columns: [number, number]
): string[] {
  const px = width * 2 * SAMPLES;
  const py = height * 4 * SAMPLES;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${px}" height="${py}" viewBox="0 0 ${VIEW_WIDTH} ${VIEW_HEIGHT}" preserveAspectRatio="none">${layer}</svg>`;
  const image = new Resvg(svg, { background: "white" }).render();
  // Read once: the getter copies the whole image every time it is called.
  const pixels = image.pixels;
  const ink = (x: number, y: number): boolean => {
    let dark = 0;
    for (let j = 0; j < SAMPLES; j++)
      for (let i = 0; i < SAMPLES; i++) {
        const offset = ((y * SAMPLES + j) * image.width + x * SAMPLES + i) * 4;
        if ((pixels[offset] ?? 255) < 128) dark++;
      }
    return dark >= SAMPLES * SAMPLES * THRESHOLD;
  };
  const rows: string[] = [];
  for (let r = 0; r < height; r++) {
    let row = "";
    for (let c = columns[0]; c < columns[1]; c++) {
      let bits = 0;
      for (let y = 0; y < 4; y++)
        for (let x = 0; x < 2; x++)
          if (ink(c * 2 + x, r * 4 + y)) bits |= BITS[y]?.[x] ?? 0;
      row += String.fromCodePoint(0x2800 + bits);
    }
    rows.push(row);
  }
  return rows;
}

function buildSize(svg: string, width: number, height: number): LogoSize {
  const all = paths(svg);
  const mark = all.slice(0, MARK_PATHS).join("");
  const word = all.slice(MARK_PATHS).join("");
  const markWidth = Math.ceil((MARK_EDGE * width) / VIEW_WIDTH);
  const frames: string[][] = [];
  for (let i = 0; i < FRAMES; i++) {
    const scale = Math.max(Math.abs(Math.cos((i * Math.PI) / FRAMES)), 0.05);
    const turned = `<g transform="translate(${MARK_AXIS} 0) scale(${scale.toFixed(4)} 1) translate(${-MARK_AXIS} 0)">${mark}</g>`;
    frames.push(braille(turned, width, height, [0, markWidth]));
  }
  return {
    width,
    height,
    markWidth,
    word: braille(word, width, height, [markWidth, width]),
    mark: frames,
  };
}

function buildLogo(svg: string): Logo {
  return {
    full: buildSize(svg, SIZES.full.width, SIZES.full.height),
    compact: buildSize(svg, SIZES.compact.width, SIZES.compact.height),
  };
}

function renderModule(logo: Logo): string {
  return `// Generated by scripts/build-logo.ts from assets/brand/turbine-logo.svg (npm run logo:build).
// Don't edit by hand: a test checks this file matches the generator.

type LogoSize = {
  width: number;
  height: number;
  markWidth: number;
  word: readonly string[];
  mark: readonly (readonly string[])[];
};

const LOGO: { full: LogoSize; compact: LogoSize } = ${JSON.stringify(logo, null, 2)};

export { LOGO };
export type { LogoSize };
`;
}

if (import.meta.main) {
  const svg = readFileSync(
    new URL("../assets/brand/turbine-logo.svg", import.meta.url),
    "utf8"
  );
  writeFileSync(
    new URL("../src/ui/logo-frames.ts", import.meta.url),
    renderModule(buildLogo(svg))
  );
}

export { buildLogo, renderModule };
export type { Logo, LogoSize };
